import {
  Activity,
  AreaChart,
  Award,
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  Bike,
  Calendar,
  ChartBar,
  ChartPie,
  Clock,
  Compass,
  Crosshair,
  Crown,
  Dumbbell,
  BarChartBig,
  Flame,
  Goal,
  HeartPulse,
  LineChart,
  Map,
  Medal,
  Mountain,
  PersonStanding,
  PieChart,
  Play,
  Radar,
  Route,
  ScatterChart,
  Shirt,
  Shovel,
  Snowflake,
  SparkleIcon,
  Target,
  TimerReset,
  Trophy,
  Waves,
  Weight,
  Zap,
  Locate,
  Footprints,
  Timer,
  Flag
} from "lucide-react";

const ICONS = [
  { id: "activity", icon: <Activity className="h-5 w-5" />, label: "Activity" },
  { id: "area-chart", icon: <AreaChart className="h-5 w-5" />, label: "Area Chart" },
  { id: "award", icon: <Award className="h-5 w-5" />, label: "Award" },
  { id: "bar-chart", icon: <BarChart className="h-5 w-5" />, label: "Bar Chart" },
  { id: "bar-chart-2", icon: <BarChart2 className="h-5 w-5" />, label: "Bar Chart 2" },
  { id: "bar-chart-3", icon: <BarChart3 className="h-5 w-5" />, label: "Bar Chart 3" },
  { id: "bar-chart-4", icon: <BarChart4 className="h-5 w-5" />, label: "Bar Chart 4" },
  { id: "bar-chart-big", icon: <BarChartBig className="h-5 w-5" />, label: "Bar Chart Big" },
  { id: "bike", icon: <Bike className="h-5 w-5" />, label: "Bike" },
  { id: "calendar", icon: <Calendar className="h-5 w-5" />, label: "Calendar" },
  { id: "chart-bar", icon: <ChartBar className="h-5 w-5" />, label: "Chart Bar" },
  { id: "chart-pie", icon: <ChartPie className="h-5 w-5" />, label: "Chart Pie" },
  { id: "clock", icon: <Clock className="h-5 w-5" />, label: "Clock" },
  { id: "compass", icon: <Compass className="h-5 w-5" />, label: "Compass" },
  { id: "crosshair", icon: <Crosshair className="h-5 w-5" />, label: "Crosshair" },
  { id: "crown", icon: <Crown className="h-5 w-5" />, label: "Crown" },
  { id: "dumbbell", icon: <Dumbbell className="h-5 w-5" />, label: "Dumbbell" },
  { id: "flame", icon: <Flame className="h-5 w-5" />, label: "Flame" },
  { id: "goal", icon: <Goal className="h-5 w-5" />, label: "Goal" },
  { id: "heart-pulse", icon: <HeartPulse className="h-5 w-5" />, label: "Heart Pulse" },
  { id: "line-chart", icon: <LineChart className="h-5 w-5" />, label: "Line Chart" },
  { id: "locate", icon: <Locate className="h-5 w-5" />, label: "Locate" },
  { id: "map", icon: <Map className="h-5 w-5" />, label: "Map" },
  { id: "medal", icon: <Medal className="h-5 w-5" />, label: "Medal" },
  { id: "mountain", icon: <Mountain className="h-5 w-5" />, label: "Mountain" },
  { id: "person-standing", icon: <PersonStanding className="h-5 w-5" />, label: "Person Standing" },
  { id: "pie-chart", icon: <PieChart className="h-5 w-5" />, label: "Pie Chart" },
  { id: "play", icon: <Play className="h-5 w-5" />, label: "Play" },
  { id: "radar", icon: <Radar className="h-5 w-5" />, label: "Radar" },
  { id: "route", icon: <Route className="h-5 w-5" />, label: "Route" },
  { id: "scatter-chart", icon: <ScatterChart className="h-5 w-5" />, label: "Scatter Chart" },
  { id: "shirt", icon: <Shirt className="h-5 w-5" />, label: "Shirt" },
  { id: "shovel", icon: <Shovel className="h-5 w-5" />, label: "Shovel" },
  { id: "snowflake", icon: <Snowflake className="h-5 w-5" />, label: "Snowflake" },
  { id: "sparkle", icon: <SparkleIcon className="h-5 w-5" />, label: "Sparkle" },
  { id: "target", icon: <Target className="h-5 w-5" />, label: "Target" },
  { id: "timer", icon: <Timer className="h-5 w-5" />, label: "Timer" },
  { id: "timer-reset", icon: <TimerReset className="h-5 w-5" />, label: "Timer Reset" },
  { id: "trophy", icon: <Trophy className="h-5 w-5" />, label: "Trophy" },
  { id: "waves", icon: <Waves className="h-5 w-5" />, label: "Waves" },
  { id: "weight", icon: <Weight className="h-5 w-5" />, label: "Weight" },
  { id: "zap", icon: <Zap className="h-5 w-5" />, label: "Zap" },
  { id: "footprints", icon: <Footprints className="h-5 w-5" />, label: "Footprints" },
  { id: "flag", icon: <Flag className="h-5 w-5" />, label: "Flag" }
];

export default ICONS;